baseurl = "https://supreme-gg-gg.github.io"
DefaultContentLanguage = "en"
title = "Jet Chiang"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    id = "G-VFK4B3BBVX"

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

[Params] 
#  homeTitle = "Jet Chiang's Portfolio" # Set a different text for the header on the home page
  subtitle = "Building tech for human flourishment"
  mainSections = ["post","posts"]
  logo = "img/pfp.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  enableGitInfo = true
  commit = "https://github.com/supreme-gg-gg/supreme-gg-gg.github.io/tree/"
#  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Jet Chiang"
  website = "jetchiang.co"
  email = "jetjiang.ez@gmail.com"
  github = "supreme-gg-gg"
  gitlab = "supreme-gg-gg"
  linkedin = "jet-chiang"
  kaggle = "jetchiang"
#  slack = "username"
#  medium = "username"
  discord = "invite code (https://discord.gg/905404381762052137)"

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 1

[[menu.main]]
    identifier = "side-quests"
    name = "Side Quests"
    weight = 3

[[menu.main]]
    parent = "side-quests"
    name = "Podcast"
    url = "page/podcast"
    weight = 1

[[menu.main]]
    parent = "side-quests"
    name = "Blog"
    url = "page/blog/"
    weight = 2
  
[[menu.main]]
    name = "Projects"
    url = "post"
    weight = 2

# [[menu.main]]
#    name = "Research"
#    url = "page/research"
#    weight = 2

[[menu.main]]
    name = "Experience"
    url = "page/experience"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
